apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegisais

resources:
  - namespace.yaml
  - configmap.yaml
  - api.yaml
  - bff.yaml
  - web.yaml
  - workers.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - monitoring-configmaps.yaml
