apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  labels:
    app.kubernetes.io/part-of: aegisais
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bff-pdb
  labels:
    app.kubernetes.io/part-of: aegisais
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bff
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-pdb
  labels:
    app.kubernetes.io/part-of: aegisais
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
