"""fix_auth_and_vessels

Revision ID: c32b98a46d40
Revises: 004
Create Date: 2026-03-17 22:08:40.453541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c32b98a46d40'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('idx_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_timestamp', 'alerts', ['timestamp'], unique=False)
    op.drop_index(op.f('idx_itdae_geofence_risk'), table_name='itdae_geofence_zones')
    # SQLite: 003 already created raw_json as JSON; PG may still have JSONB from legacy 003.
    if not is_sqlite:
        op.alter_column(
            'itdae_positions',
            'raw_json',
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.JSON(),
            existing_nullable=True,
        )
    op.drop_index(op.f('itdae_pos_mmsi_ts'), table_name='itdae_positions')
    op.create_index('idx_itdae_pos_mmsi_ts', 'itdae_positions', ['mmsi', 'timestamp'], unique=False)
    op.create_index(op.f('ix_vessels_latest_timestamp'), 'vessels_latest', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessels_latest_timestamp'), table_name='vessels_latest')
    op.drop_index('idx_itdae_pos_mmsi_ts', table_name='itdae_positions')
    op.create_index(op.f('itdae_pos_mmsi_ts'), 'itdae_positions', ['mmsi', 'timestamp'], unique=False)
    if not is_sqlite:
        op.alter_column(
            'itdae_positions',
            'raw_json',
            existing_type=sa.JSON(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
        )
    op.create_index(op.f('idx_itdae_geofence_risk'), 'itdae_geofence_zones', ['risk_level'], unique=False)
    op.drop_index('idx_alerts_timestamp', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
