#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PYTHON_BIN="${LOCK_PYTHON_BIN:-$(command -v python3.11 || command -v python3)}"
VENV_DIR="${LOCK_VENV_DIR:-$ROOT_DIR/.lock-venv}"
OUTPUT_DIR="$ROOT_DIR"
UPGRADE_FLAG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --upgrade)
      UPGRADE_FLAG="--upgrade"
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

mkdir -p "$OUTPUT_DIR"
cd "$ROOT_DIR"

"$PYTHON_BIN" -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --quiet \
  "pip==25.3" \
  "setuptools==82.0.1" \
  "wheel==0.46.3" \
  "pip-tools==7.5.3"

runtime_raw="$(mktemp "$OUTPUT_DIR/.requirements.lock.raw.XXXXXX")"
dev_input="$(mktemp "$OUTPUT_DIR/.requirements-dev.in.XXXXXX")"
dev_only_raw="$(mktemp "$OUTPUT_DIR/.requirements-dev-only.lock.raw.XXXXXX")"
trap 'rm -f "$runtime_raw" "$dev_input" "$dev_only_raw"' EXIT

"$VENV_DIR/bin/pip-compile" \
  --quiet \
  --no-annotate \
  --generate-hashes \
  --allow-unsafe \
  --strip-extras \
  --resolver=backtracking \
  $UPGRADE_FLAG \
  --output-file "$runtime_raw" \
  pyproject.toml

python3 - <<'PY' "$runtime_raw" "$OUTPUT_DIR/requirements.lock"
import sys
from pathlib import Path

runtime_raw, runtime_out = map(Path, sys.argv[1:3])

def strip_header(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    idx = 0
    while idx < len(lines) and (not lines[idx].strip() or lines[idx].startswith("#")):
        idx += 1
    body = "\n".join(lines[idx:]).strip()
    return f"{body}\n" if body else ""

runtime_out.write_text(
    "#\n"
    "# Autogenerated by scripts/compile_lockfiles.sh from pyproject.toml.\n"
    "# Do not edit by hand.\n"
    "#\n\n"
    + strip_header(runtime_raw),
    encoding="utf-8",
)
PY

python3 - <<'PY' "$ROOT_DIR/pyproject.toml" "$dev_input" "$OUTPUT_DIR/requirements.lock"
import sys
import tomllib

pyproject_path, output_path, runtime_lock_path = sys.argv[1:4]
with open(pyproject_path, "rb") as fh:
    data = tomllib.load(fh)

dev_dependencies = data["project"].get("optional-dependencies", {}).get("dev", [])

with open(output_path, "w", encoding="utf-8") as fh:
    fh.write(f"-c {runtime_lock_path}\n")
    for dependency in dev_dependencies:
        fh.write(f"{dependency}\n")
PY

"$VENV_DIR/bin/pip-compile" \
  --quiet \
  --no-annotate \
  --generate-hashes \
  --allow-unsafe \
  --strip-extras \
  --resolver=backtracking \
  $UPGRADE_FLAG \
  --output-file "$dev_only_raw" \
  "$dev_input"

python3 - <<'PY' "$dev_only_raw" "$OUTPUT_DIR/requirements-dev.lock"
import sys
from pathlib import Path

dev_only_raw, dev_out = map(Path, sys.argv[1:3])

def strip_header(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    idx = 0
    while idx < len(lines) and (not lines[idx].strip() or lines[idx].startswith("#")):
        idx += 1
    body = "\n".join(lines[idx:]).strip()
    return f"{body}\n" if body else ""

dev_only_body = strip_header(dev_only_raw)

dev_out.write_text(
    "#\n"
    "# Autogenerated by scripts/compile_lockfiles.sh from pyproject.toml.\n"
    "# requirements.lock is the runtime base for this environment.\n"
    "# Do not edit by hand.\n"
    "#\n\n"
    "-r requirements.lock\n\n"
    + dev_only_body,
    encoding="utf-8",
)
PY
